AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Creates an AWS Lambda Function that can be used as a CloudFormation CustomResource
  to provision and verify an Amazon SES domain identity for sending and/or receiving
  email. (See the readme for more information.)

Parameters:
  LambdaCodeS3Bucket:
    Type: String
    Default: YOUR_BUCKET_NAME
    Description: >
      The S3 bucket where the LAMBDA_ZIP deployment package
      has been uploaded. Must reside in the same AWS Region where your stack
      is running.
  LambdaCodeS3Key:
    Type: String
    Default: YOUR_LAMBDA_ZIP_KEY
    Description: >
      The S3 key to the LAMBDA_ZIP deployment package.

Outputs:
  Arn:
    Description: The ServiceToken for the Custom::SES_Domain resource
    Value: !GetAtt LambdaFunction.Arn
  Name:
    Description: The AWS::Lambda::Function that implements Custom::SES_Domain
    Value: !Ref LambdaFunction

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AssumeLambdaExecutionRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      # (allows logging)
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: ProvisionSESDomainIdentities
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: AllowSESDomainIdentityProvisioning
            Effect: Allow
            Action:
            - ses:DeleteIdentity
            - ses:GetIdentityDkimAttributes
            - ses:GetIdentityMailFromDomainAttributes
            - ses:GetIdentityVerificationAttributes
            - ses:SetIdentityDkimEnabled
            - ses:SetIdentityMailFromDomain
            - ses:VerifyDomainDkim
            - ses:VerifyDomainIdentity
            Resource: "*"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: CloudFormation custom SES domain provisioning
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.6
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref LambdaCodeS3Key
